apiVersion: apps/v1
kind: Deployment
metadata:
  name: indiaproj-deployment
  labels:
    app: indiaproj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: indiaproj
  template:
    metadata:
      labels:
        app: indiaproj
    spec:
      containers:
      - name: indiaproj-container
        image: tanvipendam/indiaproj:latest
        ports:
        - containerPort: 80